
name: Mobile-Tesing-CI

on:
  push:
    branches: [ feature-mobile ]
  pull_request:
    branches: [ feature-mobile ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [28]  
        target: [default]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/setup-node@v2
      with:
       node-version: '16'
    - run: |
            npm install -g appium
            appium -v
            appium &>/dev/null &
    - name: Run Appium Tests
      uses: reactivecircus/android-emulator-runner@v2.27.0
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 6
        script: mvn clean test -Pandroid -X
      # Upload Appium Logs
    - name: Upload Appium logs
      uses: actions/upload-artifact@v1
      with:
          name: appium.log
          path: appium.log
      # Upload Test Results
    - name: Upload Test Results
      uses: actions/upload-artifact@v1
      with:
        name: e2e-results
        path: __tests__/e2e/output
